### ISSUE TITLE
dependencies to build missing

### ISSUE THREAD

**Issue by cinnamoncoin** [BlueDragon747/eloipool_Blakecoin#1]
some of the necessary files to build are no longer where they were, some i cannot locate at all

python base 58 now here https://gitlab.com/bitcoin/python-base58.git

midstate    is not around  -- my experiment is over for tonight,  also 
not required to build but luke's orig  code https://gitorious.org/~Luke-Jr/bitcoin/luke-jr-bitcoin/blobs/namecoin_mmm/contrib/merged-mine-proxy
is mia !!!

**Comment by BlueDragon747** [comment]
dont need midstate its for sha256 and the merge mine proxy is included in
my eloipool as it needed modification for more than 1 aux
https://github.com/BlueDragon747/eloipool_Blakecoin/blob/master/merged-mine-proxy.py

**Comment by cinnamoncoin** [comment]
Thanks Blue !! I was following the 'stock' directions :-)
Will close this + have another go at it !

**Comment by BlueDragon747** [comment]
Added to my Github and updated the readme for eloipool dependencies

python-base58: https://github.com/BlueDragon747/python-base58
python-bitcoinrpc: https://github.com/BlueDragon747/python-bitcoinrpc

**Comment by cinnamoncoin** [comment]
merged to my repo , thanks blue
